# Generated by Django 5.1.6 on 2025-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_project_end_time_alter_project_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='activity',
            field=models.CharField(choices=[('General', 'General'), ('Development', 'Development'), ('Testing', 'Testing'), ('Deployment', 'Deployment')], default='General', max_length=255),
        ),
    ]
