# Generated by Django 5.1.6 on 2025-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_project_updated_at_alter_project_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
